### ISSUE TITLE
How to setup ERGO on WINDOWS Sir ?

### ISSUE THREAD

**Issue by superinka** [cristianoliveira/ergo#102]

**Comment by cristianoliveira** [comment]
Hello @superinka .

First of all, sorry for the absent. 
I am not an Windows user but I will try to help you anyway. In order to install it in that system, you have to download the `ergo.exe` from the [releases](https://github.com/cristianoliveira/ergo/releases) and place it probably inside the "C:/Program Files" but I am not sure. :(

Or you can download the executable and run it on the folder you have it.
