### ISSUE TITLE
"sh: [FATAL] armv7l is not yet supported" when installing on Raspberry pi 4, running raspbian.

### ISSUE THREAD

**Issue by GingerGigiCat** [cristianoliveira/ergo#124]
When running `curl -s https://raw.githubusercontent.com/cristianoliveira/ergo/master/install.sh | sh` in the terminal on a raspberry pi 4, it returns:
```
Using /tmp to store downloaded file
sh: [FATAL] armv7l is not yet supported
Downloading version v0.2.5 from repo
sh: [FATAL] unable to download package
```
This is a problem because I use my raspberry pi to host my server, and it is the only computer that keep powered on 24/7.

**Comment by cristianoliveira** [comment]
Hey @GingerGigiCat 

Ergo has no built version that supports Raspberry pi at the moment. Since ergo is built using golang, you can try to compile a version for it. Like this https://www.thepolyglotdeveloper.com/2017/04/cross-compiling-golang-applications-raspberry-pi/

What are you trying to achieve? I wonder if NGINX isn't better a tool for this usage https://engineerworkshop.com/blog/setup-an-nginx-reverse-proxy-on-a-raspberry-pi-or-any-other-debian-os/

**Comment by GingerGigiCat** [comment]
@cristianoliveira Thanks, I will try NIGNX, it sounds like it can do what I am looking for.
