### ISSUE TITLE
In tests use `ergo` from $PATH than relative path.

### ISSUE THREAD

**Issue by sitaramshelke** [cristianoliveira/ergo#24]
While trying to understand the code, I tried to run the tests. There we are looking for `ergo` binary using relative path in `ergo_run_test.go`. Can we simply replace it `ergo`, since we might already have it installed in out $PATH?

**Comment by cristianoliveira** [comment]
Hey @sitaramshelke thanks for pointing that out. It seems that is a problem on the test flow indeed. We don't see that happening on `travis.ci` buildings cause it always build before testing. I am not sure if we can use the binary installed on current '$PATH' because we can't ensure that it has the last version. 

I think these tests deserve a refactor but for now, we can basically ensure that we are building before testing. In order to ensure it we can include it into Makefile:
```makefile
test: build
	@go test ./... -v
```
and then use `make test` for testing

I accept suggestions also. :)

**Comment by sitaramshelke** [comment]
Ah, I did not consider CI part. Running make tasks seems good to me. IMO can we have a `contribution.md` with little info about the steps and tasks that need to be run?

**Comment by cristianoliveira** [comment]
Totally agree. I will open a issue for it. It should a contains step by step instruction for cloning it, building and testing.

**Comment by srini156** [comment]
@cristianoliveira - I also encountered this issue on my local. I tried using `$GOPATH/bin/ergo` but didn't work for me. If you are looking for contributions, perhaps I could help again 👍

**Comment by cristianoliveira** [comment]
Hey @srini156 we already solved this problem :)
Sure, any help would be great.
