### ISSUE TITLE
bug: Command ergo -v doesn't show the version

### ISSUE THREAD

**Issue by hmleal** [cristianoliveira/ergo#78]
run:
```sh
ergo -v
```

output:
```
# A simple blank line
```

**Comment by cristianoliveira** [comment]
How have you installed ergo? 
The var `VERSION` is only filled when a build is made. 

https://github.com/cristianoliveira/ergo/blob/master/main.go#L15

What we can do instead is fill it by default with `WIP` or `master` instead.

**Comment by adiclepcea** [comment]
Or we could use ```git describe --always``` in the makefile.
I will try to make a small modification with a PR.

**Comment by cristianoliveira** [comment]
Hey @adiclepcea the problem here is when installing using `go get` :/ 
I think the right version, in this case, is `master` indeed cause `go get` gets directly from it. There is no version yet.

The changes made in #79 will break the flow of releasing it into homebrew (osx package manager) :/
I use `.version` as a reference for releasing it.

**Comment by adiclepcea** [comment]
Well, in #79 you still have the .version (and the bumpversion make target).
Still, while building with ```make build``` you will have an version, no mater in which branch you are.
Indeed, ```go get``` does not use any version. This also applies to ```go build``` and ```go install```.
You are right however, #79 does not solve the problem of compiling without using the make target, and I do not know how brew works behind, but ```.version``` is stil there.
Should I close it?

**Comment by cristianoliveira** [comment]
I think we can use as default the version `master` or maybe `nightly` like Rust does.
https://doc.rust-lang.org/1.13.0/book/nightly-rust.html

Once you get code from master branch we can say that it is latest version but not released yet

WDYT?

**Comment by adiclepcea** [comment]
I think that master should only hold the releases (the version tagged commits).
The develop branch should be used for accepted, but not versioned (nightly) PRs.
So that the flow would be something like: 
PRs should go against the ```develop``` branch. When we (or you) decide that a new version is ready to be release, then  a PR with the accepted changes from ```develop``` should be made against ```master```.
This way ```master``` will always hold the latest release, while ```develop``` will hold the tested, but not yet released (the nighly released).
Maybe something like https://datasift.github.io/gitflow/IntroducingGitFlow.html.
Whichever way we decide we should inform the contributors about what we choose.
This does not change the facet that a ```go build``` or ```go get``` will not add the version to the executable. We can put a default value as the version (something like _unofficial build_ perhaps). This will only be used if the version ldflag is not specified.

**Comment by alexsadliak** [comment]
I will take this one.

**Comment by cristianoliveira** [comment]
I think we can try using the gitflow. It will enable us to test some features before releasing or merging code into master. :)

Let me create this branch and update the contribution guides
